### ISSUE TITLE
Task evaluation files missing

### ISSUE THREAD

**Issue by anilbatra2185** [gyxxyg/VTG-LLM#16]
Hi @gyxxyg ,

Thank for sharing the code for the work.

I am trying to run the evaluation on Charades with the given instructions, however, the task specific evaluation files are missing in the "[METRICS](https://github.com/gyxxyg/VTG-LLM/tree/master/metrics)" folder. 

Please let me know the steps to get the files.

Thanks!

**Comment by gyxxyg** [comment]
We have updated the metric files.
