### ISSUE TITLE
Inference time on Single A100 GPU

### ISSUE THREAD

**Issue by anilbatra2185** [gyxxyg/VTG-LLM#18]
Hi @gyxxyg ,

I am running an evaluation code for ActivityNet for 3.7K validation videos, however, the inference time is quite large. I wonder if you can share the inference time and any suggestions to speed-up the inference. 

Regards
Anil

**Comment by gyxxyg** [comment]
Hi, I tried about 3k activitynet captions videos on v100 gpu, the inference time is about 1 day. Moreover, processing 96 frames is time consuming, preprocess the visual features may speed up the inference.

**Comment by anilbatra2185** [comment]
thanks for sharing the information.
