### ISSUE TITLE
The 'Image_size' is missing in eval configs

### ISSUE THREAD

**Issue by minjoong507** [gyxxyg/VTG-LLM#24]
Hi, thanks for sharing your work.

I encountered an error while running this code to evaluate the model. It appears that 'image_size' will be set according to the configs, but no evaluation configs (in [here](https://github.com/gyxxyg/VTG-LLM/tree/master/eval_configs)) contain 'image_size' in the model configurations.

So this results in `image_size` being None, causing an error when building a video encoder.

https://github.com/gyxxyg/VTG-LLM/blob/d417c1dda74ecb660e0199b81528134ae534c935/vtgllm/models/vtgllm.py#L781-L786

https://github.com/gyxxyg/VTG-LLM/blob/d417c1dda74ecb660e0199b81528134ae534c935/vtgllm/models/vit.py#L139-L142

```
num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0])
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

I think the code should be changed to `img_size = cfg.get("image_size", 224)` or set the value of `img_size` as 224 in the configuration files.

Could you provide guidance about this?

Thank you.

**Comment by gyxxyg** [comment]
Hi, please note that by default, a configuration will be set from the line [here](https://github.com/gyxxyg/VTG-LLM/blob/d417c1dda74ecb660e0199b81528134ae534c935/vtgllm/models/vtgllm.py#L165). Kindly ensure that the specified path is accurate.

**Comment by minjoong507** [comment]
Hi, @gyxxyg 

Thanks for your quick reply. 

I just fixed my code to refer to the right configuration file. and now it's working.

Thank you.
